
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '3B33AC79713AE74C203B3254CF016AA3'
    
_lr_action_items = {')':([4,5,6,9,10,11,12,],[-7,-4,-6,12,-3,-2,-5,]),'(':([0,2,7,8,],[2,2,2,2,]),'+':([1,4,5,6,9,10,11,12,],[8,-7,-4,-6,8,-3,-2,-5,]),'-':([1,4,5,6,9,10,11,12,],[7,-7,-4,-6,7,-3,-2,-5,]),'NUM':([0,2,7,8,],[4,4,4,4,]),'ID':([0,2,7,8,],[6,6,6,6,]),'$end':([1,3,4,5,6,10,11,12,],[-1,0,-7,-4,-6,-3,-2,-5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'s':([0,],[3,]),'e':([0,2,],[1,9,]),'t':([0,2,7,8,],[5,5,10,11,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> s","S'",1,None,None,None),
  ('s -> e','s',1,'p_stmt','parser.py',10),
  ('e -> e + t','e',3,'p_expr_add','parser.py',14),
  ('e -> e - t','e',3,'p_expr_sub','parser.py',18),
  ('e -> t','e',1,'p_expr_t','parser.py',22),
  ('t -> ( e )','t',3,'p_t_paren','parser.py',26),
  ('t -> ID','t',1,'p_t_ID','parser.py',32),
  ('t -> NUM','t',1,'p_t_NUM','parser.py',36),
]
